name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: prepare configure
      run: chmod +x configure
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make server
      run: make server
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
